# Generated by Django 3.0.5 on 2021-05-17 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_portal_app', '0002_auto_20210517_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
